spring.application.name=SaGa

spring.data.mongodb.uri=mongodb+srv://saimanikantakaranam682:7095835048@cluster0.fin6s.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=SaGa
spring.security.user.name=saimanikantakaranam682
spring.security.user.password=7095835048


jwt.secret=MyNameIsSaiManikantaIamStudyingDiplomaFinalYearIamAFullStackDeveloper

spring.devtools.livereload.enabled=true
spring.devtools.restart.exclude=static/**,public/**
spring.devtools.restart.enabled=true

upload.dir=./uploads

spring.servlet.multipart.enabled = true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=redcrossconnect4@gmail.com
spring.mail.password=bhsy xzgt ubey koiq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.from=redcrossconnect4@gmail.com


server.address=0.0.0.0

cloudinary.cloud-name=dmqqn9fld
cloudinary.api-key=875331722775911
cloudinary.api-secret=PwvZtGOczu-N8-URFnPvdWhcxeY